# https://taskfile.dev

version: '3'


includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs


tasks:

  list:
    desc: "Show available commands"
    aliases:
      - default
    silent: True
    cmds:
      - task --list-all

  # Fix
  # =============

  fix_lint:
    desc: fix all what can be fixed
    cmds:
      - isort --profile black --overwrite-in-place superconf
      - black superconf tests examples

  test_lint:
    desc: show what can be improved
    cmds:
      - isort --profile black superconf
      - black --check superconf tests examples
      - pylint superconf || true

  # Tests
  # =============

  test:
    desc: Test everything
    cmds:
      #- task: test_pytest
      - task: test_lab
      #- task: test_regressions
      - task: test_recap
      - task: test_lint

  test_pytest:
    desc: Test with pytest
    cmds:
      - pytest tests

  test_lab:
    dest: Test examples
    cmds:
      - bash lab/run_lab.sh

  test_regressions:
    desc: Test for regressions
    cmds:
      - pytest tests/test_50_*
      #- pytest tests/test_50_regressions_node.py
      #- pytest tests/test_50_regressions_store.py

  test_recap:
    desc: Report tests
    cmds:
      - pytest tests --tb no -vv -q
      - pytest --cov=superconf --cov-report term-missing  tests/


