# https://taskfile.dev

version: '3'


tasks:



  # Generate
  # =============

  gen_doc_class_graph:
    desc: generate superconf class diagrams
    cmds:
      - pyreverse -my -A -o png -p superconf -d docs/images/ superconf/configuration.py
      - >
        echo "Image generated in: docs/images/"
  
  # Fix
  # =============

  fix_lint:
    desc: fix all what can be fixed
    cmds:
      - isort --profile black --overwrite-in-place superconf
      - black superconf tests examples

  test_lint:
    desc: show what can be improved
    cmds:
      - isort --profile black superconf
      - black --check superconf tests examples
      - pylint superconf || true

  # Tests
  # =============

  test:
    desc: Test everything
    cmds:
      #- task: test_pytest
      - task: test_examples
      #- task: test_regressions
      - task: test_recap
      - task: test_lint

  test_pytest:
    desc: Test with pytest
    cmds:
      - pytest tests

  test_examples:
    dest: Test examples
    cmds:
      - python examples/example_104.py --debug true
      - python examples/example_105.py --debug true
      - python examples/example_106.py --debug true
      - python examples/example_107.py --debug true
      - python examples/example_108.py --debug true

  test_regressions:
    desc: Test for regressions
    cmds:
      - pytest tests/test_50_*
      #- pytest tests/test_50_regressions_node.py
      #- pytest tests/test_50_regressions_store.py

  test_recap:
    desc: Report tests
    cmds:
      - pytest tests --tb no -vv -q
      - pytest --cov=superconf --cov-report term-missing  tests/


