# https://taskfile.dev

version: '3'

tasks:


  # Fix
  # =============

  fix_lint:
    desc: fix all what can be fixed
    cmds:
      - black superconf tests examples
      - isort --overwrite-in-place superconf

  test_lint:
    desc: show what can be improved
    cmds:
      - pylint superconf || true
      - black --check --diff superconf tests examples || true
      - isort superconf || true

  # Tests
  # =============

  test:
    desc: Test everything
    cmds:
      - task: test_pytest
      - task: test_examples
      - task: test_regressions
      - task: test_recap

  test_pytest:
    desc: Test with pytest
    cmds:
      - pytest tests

  test_examples:
    dest: Test examples
    cmds:
      - python examples/example_104.py --debug true
      - python examples/example_105.py --debug true
      - python examples/example_106.py --debug true
      - python examples/example_107.py --debug true
      - python examples/example_108.py --debug true

  test_regressions:
    desc: Test for regressions
    cmds:
      - pytest tests/test_regressions_node.py
      - pytest tests/test_regressions_store.py

  test_recap:
    desc: Report tests
    cmds:
      - pytest tests --tb no -vv -q
      - pytest --cov=superconf --cov-report term-missing  tests/


