---
# https://taskfile.dev

version: '3'


includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs

tasks:

  list:
    desc: "Show available commands"
    aliases:
      - default
    silent: true
    cmds:
      - task --list-all

  # Publish and release
  # =============

  publish_pypi_test:
    desc: Publish package on test.pypi.org
    cmds:
      - poetry build
      - poetry publish -r testpypi


  publish_pypi:
    desc: Publish package on pypi.org
    cmds:
      - poetry build
      - poetry publish


  # Fix
  # =============

  fix_lint:
    desc: fix all what can be fixed
    cmds:
      - isort --profile black --overwrite-in-place superconf
      - black superconf tests
      - pymarkdownlnt fix $( git ls-files | grep 'md$' )

  test_lint:
    desc: show what can be improved
    cmds:
      - isort --profile black superconf
      - black --check superconf tests
      - pylint superconf || true
      - yamllint $( git ls-files | grep 'yml$' )
      - pymarkdownlnt scan $( git ls-files | grep 'md$' )

  # Tests
  # =============

  test:
    desc: Test everything
    cmds:
      # - task: test_pytest
      - task: test_lab
      # - task: test_regressions
      - task: test_recap
      - task: test_lint

  test_pytest:
    desc: Test with pytest
    cmds:
      - pytest tests

  test_lab:
    dest: Test examples
    cmds:
      - bash lab/run_lab.sh

  test_regressions:
    desc: Test for regressions
    cmds:
      - pytest tests/test_50_*

  test_recap:
    desc: Report tests
    cmds:
      - pytest tests --tb no -vv -q
      - pytest --cov=superconf --cov-report term-missing  tests/

