---
# https://taskfile.dev

version: '3'

tasks:

  list:
    desc: "Show available commands"
    aliases:
      - default
    silent: true
    cmds:
      - task --list-all

  # Generate
  # =============

  prep_doc:
    desc: Prepare documentation assets
    cmds:
      - task: copy_readme
      - task: copy_logo
      - task: gen_class_graph
      - task: gen_adr_toc

  copy_logo:
    desc: inject logo into documentation
    cmds:
      - cp -R ../logo/. content/logo

  copy_readme:
    desc: inject readme into documentation
    cmds:
      - cp -R ../README.md content/index.md

  gen_adr_toc:
    desc: generate adr toc
    preconditions:
      - command -v adr
    cmds:
      - adr generate toc > content/architecture/list.md

  gen_class_graph:
    desc: generate superconf class diagrams
    cmds:
      - mkdir -p content/images
      - pyreverse -my -A -o svg -p superconf -d content/images/ ../superconf/
      - for:
          - configuration
          - fields
          - loaders
          - casts
          - anchors
          - extra/xdg
        cmd: |
          mkdir -p content/images/schema_{{.ITEM | replace "/" "_" }}
          pyreverse -my -A -o svg \
            -p superconf \
            -d content/images/schema_{{.ITEM | replace "/" "_"}} \
            ../superconf/{{.ITEM}}.py
      - >
        echo "Image generated in: content/images/"

  # Mkdocs
  # =============

  serve:
    desc: serve mkdoc website locally
    cmds:
      - task: prep_doc
      - mkdocs serve

  publish:
    desc: update gh_page branch with new documentation
    cmds:
      - task: prep_doc
      - poetry run mkdocs gh-deploy --force

